### ISSUE TITLE
Group picker is missing from the Group field in edit mode which prevents sending messages

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-flashmessages#11]
STEPS TO REPRODUCE

1. Login with Admin
2. Go to Flash Messages App from Apps Panel
3. Click on 'Create'
4. Type a name for the new flash message
5. Select 'Flash Messages' page type
6. Click 'Create'
7. Select a Start Date (e.g. Now)
8. Click in Groups field and type a group name (e.g. XWikiAllGroup)
9. Write a message
10. Click 'Save & View'

EXPECTED RESULTS

The flash message popup is displayed on the center of the screen and also below the navigation bar (since the present date and time was selected).

ACTUAL RESULTS

In edit mode, the GROUPS field is missing the Group picker, therefore the flash message cannot be displayed.

![flash_edit_no_group_picker_10_6_1](https://user-images.githubusercontent.com/32512703/43838058-0009ec66-9b23-11e8-8df5-c323429e646d.jpg)

I've tested also on XWiki 10.4 (with the old group picker) and the issue could not be reproduced.

Environment: Windows 10 Pro 64 bit, Chrome 68, using a local instance of XWiki 10.6.1 on Oracle 11.2

**Comment by mflorea** [comment]
Fixed in 79b158b7df435f04d136ba547aa7272e2ad3df0b.
