### ISSUE TITLE
Images not showing in the pop-up box and also can't see the images uploaded with another browser

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-flashmessages#21]
Steps to reproduce:

1. Click on Create
2. Add a title
3. Click on Create
4. Choose Start Date > Now and Groups > XWikiAllGroup
5. In the Message box click on Image
6. Upload a new image from your device
7. Click Save & View

Expected results: The image is shown in the pop-up and in the top menu.

Actual results: The image is not shown in the pop-up. Syntax is shown instead. Also, when accessing the wiki with another browser the image uploaded doesn't show in the top menu either - only the name of the image, tried this with IE 11 and Chrome 69.

Environment: Windows 10, XWiki 10.8.1 with MySQL 5.7 and IE 11 also Chrome 69

![newflashimageie11result](https://user-images.githubusercontent.com/40691112/47164424-b2eae780-d300-11e8-9a2b-29f3c236ae44.jpg)
![flashimageie11result](https://user-images.githubusercontent.com/40691112/47164421-b2525100-d300-11e8-8e5c-f0dcad7d11dd.jpg)
![otherbrowser](https://user-images.githubusercontent.com/40691112/47164595-00675480-d301-11e8-94f1-ba1e42977a41.jpg)

**Comment by arcilli** [comment]
FIxed in #31.
