### ISSUE TITLE
The 'Groups' drop-down filter box should display only groups added on entries (instead of all existing groups on the wiki)

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-flashmessages#26]
Preconditions: The XWiki instance has some groups already created (e.g. G1, G2, G3).

STEPS TO REPRODUCE

1. Go to Flash Messages App
2. Create a flash entry by filling the 'Groups' with a group (e.g. G1)
3. Create another flash entry by filling other group (e.g. XWikiAdminGroup)
4. Go to Flash Messages homepage
5. Click on drop-down box from the 'Groups' column on the live table

EXPECTED RESULTS

The drop-down box displays for filtering only the groups that were added in the existing entries (e.g. G1 and XWikiAdminGroup).

ACTUAL RESULTS

In drop-down box there are displayed all the existing groups from the wiki (screenshots attached).

![flash_groups1](https://user-images.githubusercontent.com/32512703/51255145-4dfc6780-19ab-11e9-821e-5c0390d0dd42.jpg)

![flash_groups2](https://user-images.githubusercontent.com/32512703/51255152-52288500-19ab-11e9-9b3b-729a57ede9af.jpg)

Environment: Windows 10 Pro 64 bit, Chrome 71, using a local instance XWiki 10.8.3 on PostgreSQL 10

**Comment by arcilli** [comment]
Partially solved in #37. After discussions with @acotiuga, we decided to offer all the list with groups (in case that an user want to filter the messages and no result is found for that group, he should see that it's no result).

**Comment by acotiuga** [comment]
Displaying all the groups seems to be the default behavior in the product. I'm not in favor of changing it here and even if we would do so, we have to update all the other extensions in order to keep a consistent feature. I'm closing this issue as the proposed fix represents also a big improvement.
