### ISSUE TITLE
Cannot configure the app from Administration

### ISSUE THREAD

**Issue by evalica** [xwikisas/application-flashmessages#3]
Message displayed: "You don't have permission to configure this application."
<img width="802" alt="current" src="https://user-images.githubusercontent.com/629552/33126140-0e4af04e-cf8c-11e7-8c92-89882c02491f.png">

**Comment by acotiuga** [comment]
![nolicense](https://user-images.githubusercontent.com/8121819/33209083-f6b854a2-d11c-11e7-8f29-423fd80b2190.png)

**Comment by acotiuga** [comment]
![withlicense](https://user-images.githubusercontent.com/8121819/33209197-7470a0a2-d11d-11e7-8670-e9364b6b8d61.png)

**Comment by acotiuga** [comment]
You can see that since the AWM way of creating flash messages was replaced by the template provider way, it is not possible anymore to create new flash messages from the Administration section. What should we do now?

**Comment by evalica** [comment]
Ideally it would be nice for Administration to have an extension point and to be able to insert the Add button for Flash entries there. 

We might need to add the button and test to be displayed only on Administration.

**Comment by mflorea** [comment]
You should be able to detect that you are inside the administration and display an Add button just in this case.

**Comment by acotiuga** [comment]
![withcreatebutton](https://user-images.githubusercontent.com/8121819/33267519-7cd2234e-d382-11e7-9425-c3ce97b47428.png)
