### ISSUE TITLE
Deleting Flash entries from the LiveTable results in empty flash messages remaining in the top bar

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-flashmessages#30]
Steps to reproduce:

1. Create some flash entries
2. From the LiveTable delete all expect 1
3. Observe the top bar

Expected results: Only the remaining Flash entrie can be seen in the LiveTable and in the top bar.

Actual results: In the top bar all the deleted flash entries appear as empty messages which change after 10 seconds as they were still there.

Environment: Windows 10, XWiki 10.11.2 with MySQL 5.7 and Edge 18

![emptyflashmessages](https://user-images.githubusercontent.com/40691112/53177979-ac93b180-35f9-11e9-9945-8c33a32ae8f7.jpg)

**Comment by arcilli** [comment]
Cannot reproduce the bug in XWiki 8.4/11.5 on Ubuntu.
The problem was probably generated, by list elements and not by the messages. This bug was solved in  #31.
