### ISSUE TITLE
Can't separate Flash messages on different lines

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-flashmessages#32]
Steps to reproduce:

1. Create a new Flash entry with paragraphs on different lines
2. Select the Start date > now and Groups > XWikiAllGroup

Expected results: The paragraphs appear on different lines as added.

Actual results: The paragraphs don't appear in different lines.

Environment: Windows 10, XWiki 10.11.2 with MySQL 5.7 and Edge 18

![diffrentlines](https://user-images.githubusercontent.com/40691112/53181827-fd5ad880-3600-11e9-8a10-eec52ad18fac.jpg)

**Comment by arcilli** [comment]
Fixed in #31.
