### ISSUE TITLE
New empty line appears after installing the Flash Message PRO

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-flashmessages#33]
After installing the Flash Message PRO an empty line appears after the header which makes the whole page go down a bit.

![emptyline](https://user-images.githubusercontent.com/40691112/53333999-22509380-3900-11e9-8c2e-4b20a4e36b8d.jpg)
![noline](https://user-images.githubusercontent.com/40691112/53334045-48763380-3900-11e9-80d1-eec154e695b2.jpg)

**Comment by ilieandriuta** [comment]
The empty line is more visible if a Menu is added after the page header like in the following:

![Empty_line](https://user-images.githubusercontent.com/32512703/56500124-4bf9f580-6512-11e9-864c-192f1a48ec27.jpg)

Reproduced on XWiki 10.11.6 on Jetty/PostgreSQL 11/IE11
