### ISSUE TITLE
Flash functionality changed from default Repeat "No" to "Yes"

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-flashmessages#42]
Expected results: When creating a new Flash message the Repeat option is set to "No" by default.

Actual results: It appears that with the latest changes/release the Repeat is automatically set to Yes by default with Repeat Interval Weekly, Repeat Frequency to 1 and Repeat Days to Monday. This is not documented as a request change and it causes issues to the tests on this app.

Environment: Windows 10, XWiki 11.3.6 Standard, Chrome 78, Flash Messages Application (Pro) 1.4.7

![NewOptions](https://user-images.githubusercontent.com/40691112/69733225-ae187a00-1135-11ea-9b66-d1c078e97bce.jpg)

**Comment by oanalavinia** [comment]
Regression caused by the fix of #23
