### ISSUE TITLE
The 'groups' column filter (select input) causes a Java Heap error in wikis with large amounts of groups

### ISSUE THREAD

**Issue by Enygma2002** [xwikisas/application-flashmessages#49]
Because of the type of the `groups column (`'groups': {'type': 'list',`), the livetable macro generates the select filter which is causing problems when the wiki has a huge number of groups (e.g. 100K) and all of them are loaded into memory to be displayed as select options.

Changing the type to `text` keep the column without the problem filter. If we want to keep the filtering helper, the select could maybe be replaced with a suggest text input, showing suggestions based on the user's input.

The screenshot is from an older version, but the problem is present in the latest version as well:
![flash-messages-manyGroups-javaHeapError](https://user-images.githubusercontent.com/709298/93461082-e2d80680-f8ec-11ea-902d-d96e679e9269.png)

**Comment by mflorea** [comment]
``suggest`` type is available since 9.8. We should use it.
