### ISSUE TITLE
Administrator doesn't have Edit right on Flash Messages Application

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-flashmessages#8]
STEPS TO REPRODUCE

Preconditions: Have a fresh XWiki instance.

1.  Login as Admin
2.  Go to Administer Wiki > Extensions > Extensions
3.  Install Flash Messages Application (Pro)
4.  Go to Administer Wiki > Extensions > Licenses
5.  Fill the required fields (First Name, Last Name, Email)
6.  Click 'Get Trial' to obtain a trial license
7.  Go to Flash Messages App from Applications Panel
8.  Add an entry

EXPECTED RESULTS

The new entry is added and is displayed in 'Flash entries' Livetable.

ACTUAL RESULTS

The Admin cannot add an entry as it doesn't have the Edit right on the application's page (has also no Edit button), although, in 'Administer Page > Rights: Page & Children' and 'Rights: Page' the Edit right is granted to 'XWikiAdminGroup' which Admin is part of. 

Environment: Windows 10 Pro 64 bit, IE11, using a local instance of XWiki 10.3 on Oracle 11.2

![flash_messages_no_add_entry](https://user-images.githubusercontent.com/32512703/39360665-c7eb9f2e-4a27-11e8-83f0-a11aaeb9ec2e.jpg)

**Comment by acotiuga** [comment]
The users should use the `Create` button and select from there the corresponding template.  The edit right is denied only on technical pages, as a means of protection so no one is able to break the application. All the new entries will be editable.
